Deploy test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,22 +20,20 @@ jobs:
 
       - name: Temporarily save files
         run: |
-          mkdir temp_directory
-          cp -R HP/* temp_directory/
-          ls -al temp_directory  # Debugging line
+          mkdir -p $GITHUB_WORKSPACE/temp_directory
+          cp -R $GITHUB_WORKSPACE/HP/* $GITHUB_WORKSPACE/temp_directory/
 
       - name: Deploy 🚀
         env:
           GITHUB_TOKEN: ${{ secrets.GH_PAT }}
         run: |
+          cd $GITHUB_WORKSPACE
           git fetch origin gh-pages
           git checkout gh-pages
-          ls -al  # Debugging line
           rm -rf *
-          cp -R temp_directory/* .
-          ls -al  # Debugging line
+          cp -R $GITHUB_WORKSPACE/temp_directory/* $GITHUB_WORKSPACE/
           git add .
-          git commit -m "Automated GitHub Pages deployment" || true
+          git commit -m "Automated GitHub Pages deployment" || true  # || true ensures that the action doesn't fail if there's nothing to commit
           if [[ -n "$GITHUB_TOKEN" ]]; then
             git push https://${GITHUB_TOKEN}@github.com/meiostudio/HPv2.git gh-pages --force
           else
