Deploy test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -22,14 +22,12 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GH_PAT }}
         run: |
-          pwd
-          ls -la  # ディレクトリリスティング
           git fetch origin gh-pages
           git checkout gh-pages
-          rm -rf *
-          cp -R HP/* .
+          rm -rf *  # Remove all files in current directory, except for the .git directory
+          cp -R HP/* .  # Copy new files from HP directory
           git add .
-          git commit -m "Automated GitHub Pages deployment" || true
+          git commit -m "Automated GitHub Pages deployment" || true  # true ensures the script continues even if commit fails (nothing to commit)
           if [[ -n "$GITHUB_TOKEN" ]]; then
             git push https://${GITHUB_TOKEN}@github.com/meiostdio/HPv2.git gh-pages
           else
